// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package test

import (
	"context"
	"github.com/LyricTian/gin-admin/v10/internal/ddd/rbac/repo"
	"github.com/LyricTian/gin-admin/v10/internal/wirex"
)

// Injectors from wire.go:

func BuildRepo(ctx context.Context) (*RepoTest, func(), error) {
	db, cleanup, err := wirex.InitDB(ctx)
	if err != nil {
		return nil, nil, err
	}
	menuRepo := &repo.MenuRepo{
		DB: db,
	}
	menuResourceRepo := repo.MenuResourceRepo{
		DB: db,
	}
	userRepo := &repo.UserRepo{
		DB: db,
	}
	userRoleRepo := repo.UserRoleRepo{
		DB: db,
	}
	roleRepo := &repo.RoleRepo{
		DB: db,
	}
	roleMenuRepo := &repo.RoleMenuRepo{
		DB: db,
	}
	repoTest := &RepoTest{
		MenuRepo:         menuRepo,
		MenuResourceRepo: menuResourceRepo,
		UserRepo:         userRepo,
		UserRoleRepo:     userRoleRepo,
		RoleRepo:         roleRepo,
		RoleMenuRepo:     roleMenuRepo,
	}
	return repoTest, func() {
		cleanup()
	}, nil
}
