// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wirex

import (
	"context"
	"github.com/HotHat/gin-admin/v10/internal/ddd/rbac/api"
	"github.com/HotHat/gin-admin/v10/internal/ddd/rbac/repo"
	"github.com/HotHat/gin-admin/v10/internal/ddd/rbac/service"
	"github.com/HotHat/gin-admin/v10/internal/ddd/route/admin"
	"github.com/HotHat/gin-admin/v10/pkg/util"
)

// Injectors from wire.go:

func BuildInjector(ctx context.Context) (*Injector, func(), error) {
	cacher, cleanup, err := InitCacher(ctx)
	if err != nil {
		return nil, nil, err
	}
	auther, cleanup2, err := InitAuth(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	db, cleanup3, err := InitDB(ctx)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	userRepo := &repo.UserRepo{
		DB: db,
	}
	userRoleRepo := &repo.UserRoleRepo{
		DB: db,
	}
	trans := &util.Trans{
		DB: db,
	}
	menuRepo := &repo.MenuRepo{
		DB: db,
	}
	userService := &service.UserService{
		Cache:        cacher,
		Trans:        trans,
		UserRepo:     userRepo,
		UserRoleRepo: userRoleRepo,
		MenuRepo:     menuRepo,
	}
	authService := &service.AuthService{
		Cache:        cacher,
		Auth:         auther,
		UserRepo:     userRepo,
		UserRoleRepo: userRoleRepo,
		UserService:  userService,
	}
	menuResourceRepo := &repo.MenuResourceRepo{
		DB: db,
	}
	roleRepo := &repo.RoleRepo{
		DB: db,
	}
	casbinx := &admin.Casbinx{
		Cache:            cacher,
		MenuRepo:         menuRepo,
		MenuResourceRepo: menuResourceRepo,
		RoleRepo:         roleRepo,
	}
	adminHandler, cleanup4, err := admin.InitAdminHandler(ctx, authService, casbinx)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	loginAPI := &api.LoginAPI{
		AuthService: authService,
	}
	userAPI := &api.UserAPI{
		UserService: userService,
		AuthService: authService,
	}
	roleMenuRepo := &repo.RoleMenuRepo{
		DB: db,
	}
	menuService := &service.MenuService{
		Cache:            cacher,
		Trans:            trans,
		MenuRepo:         menuRepo,
		MenuResourceRepo: menuResourceRepo,
		RoleMenuRepo:     roleMenuRepo,
	}
	menuAPI := &api.MenuAPI{
		MenuService: menuService,
	}
	roleService := &service.RoleService{
		Cache:        cacher,
		Trans:        trans,
		RoleRepo:     roleRepo,
		RoleMenuRepo: roleMenuRepo,
		UserRoleRepo: userRoleRepo,
	}
	roleAPI := &api.RoleAPI{
		RoleService: roleService,
	}
	rbacRouteV1 := &admin.RBACRouteV1{
		Handler:  adminHandler,
		LoginAPI: loginAPI,
		UserAPI:  userAPI,
		MenuAPI:  menuAPI,
		RoleAPI:  roleAPI,
	}
	injector := &Injector{
		RBACRouteV1: rbacRouteV1,
	}
	return injector, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
